### ISSUE TITLE
App crashes when trying to run after download with gh

### ISSUE THREAD

**Issue by doza62** [visini/timebox#2]
I downloaded with gh then unzipped the file. Error message appeared:
![image](https://user-images.githubusercontent.com/14064394/104367615-73b49c80-54f1-11eb-8592-a4fdce6cc739.png)

Console shows:
```
error	16:13:03.563093-0400	sharingd	Trying to grab power assertion while we already have one
error	16:13:07.606209-0400	tccd	FAIL: PID[62940]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
error	16:13:07.606456-0400	tccd	FAIL: PID[62940]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
error	16:13:07.613550-0400	tccd	FAIL: PID[62940]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
error	16:13:07.613970-0400	tccd	FAIL: PID[62940]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
error	16:13:07.629590-0400	tccd	FAIL: PID[62940]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
error	16:13:07.629983-0400	tccd	FAIL: PID[62940]: SecTaskCopySigningIdentifier(): [22: Invalid argument]
error	16:13:07.636392-0400	tccd	Failed to copy signing info for 62940, responsible for file:///Users/rodri/Downloads/Timebox.app/Contents/MacOS/Timebox: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"
error	16:13:07.668242-0400	kernel	Sandbox: tccd(133) deny(1) system-fsctl _IO('h', 47)
error	16:13:08.934231-0400	Safari	Failed to create a remote object proxy for extension (<private>) with reason (ExtensionConnectionReasonToolbarItemValidation): Error Domain=NSCocoaErrorDomain Code=4099 "Couldn’t communicate with a helper application."
```

Then a bunch of errors from kernel with messages like: 
> Sandbox: logo_helper(238) deny(1) file-read-data {PATH}/Timebox.app/Contents/*

**Comment by visini** [comment]
Hi @R0dri, thank you for opening this issue and investigating. Please let me know:

- Are you using the latest release (0.4.1)?
- Which version of [Things 3](https://culturedcode.com/things/) are you using?
- Which version of macOS are you using?

Thank you!

**Comment by doza62** [comment]
Oh, probably that is my mistake. I don't have Things 3. I guess I didn't really understand the project. I just wanted a simple Pomodoro app mock up I can integrate with another app.

**Comment by visini** [comment]
No worries, thanks for following up!

You might be interested in [visini/pomodoro](https://github.com/visini/pomodoro) to start from scratch with a very basic pomodoro timer – and then add your logic to integrate it with another app. See [my blog post](https://camillovisini.com/article/create-macos-menu-bar-app-pomodoro/) where I discuss the basic functionality of `rumps` and `py2app`.

On the other hand, you might take a look at this repository's code and adapt it to your needs. Things 3 uses a SQLite database, from where the individual tasks are extracted. 

Have fun! Closing this issue for now.

**Comment by doza62** [comment]
I've looked into it. It looks great! im testing it at the moment. Looking forward to see how it handles notifications with the new Notification Center.

If you are interested, I will be adding webhook or add a companion app I can set up in an online server so when this app begins, it can poll data from the companion app and update itself at startup. 

The purpose of that project is integrating with ClickUp, it has a powerful API so I want to sync the current task I am tracking time with this Pomodoro app so I can see it at the menu bar.
